import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/common/Sidebar";
import NavHeader from "@/components/common/NavHeader";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <body className="flex">
        <Sidebar />
        <div className="flex-1 bg-[#E5E5E5]">
          <NavHeader />
          <div className="px-3.5 py-3.5">
          {children}
          </div>
        </div>
      </body>
    </html>
  );
}
